### PR TITLE
Add Blog Post on Test Framework

### PR DESCRIPTION
**Pull request by vasireddy99**
This PR is to add blog post on the test framework
 * Refactor the blog posts folder structure.
 * Add authors to the release blog post .

Tested the changes for the folder structure in local

image

### CODE REVIEW

**Review by alolita — COMMENTED** [review]
@vasireddy99 was this change tested?

**Comment by vasireddy99** [comment]
> 

Yes Alolita, I have tested this change, shall make this PR `ready for review` after committing all changes

**Review by alolita — COMMENTED** [review]
Naming convention for release posts should be:

aws-distro-for-opentelemetry-<component>-<version>.xxx

for example <component> can be collector, lambda-layer, operator, java-agent etc.
and <version> can be 0.17.0, future version numbers

**Comment by bryan-aguilar** [comment]
This seems like a lot more than just a single blog post for the test framework. The title should be changed or the PR should be split.

**Comment by vasireddy99** [comment]
> This seems like a lot more than just a single blog post for the test framework. The title should be changed or the PR should be split.

yes, that's right, will have to rename the title.

**Review by alolita — APPROVED** [review]

**Pull request merged**
