### PR TITLE
Adding ADOT lambda metrics support doc

### PR DESCRIPTION
**Pull request by shaochengwang**
Adding ADOT lambda metrics support doc

Feature Reference: https://github.com/aws-observability/aws-otel-lambda/pull/15

### CODE REVIEW

**Comment by mxiamxia** [comment]
/hold

We'll hold this metric support in Lambda layer docs and it will be merged when it is ready for the future launches.

**Review by alolita — APPROVED** [review]
Made minor edits. Will merge 4/29.

**Comment by alolita** [comment]
This is on-hold for now.

**Comment by alolita** [comment]
Stale PR - let's reopen when ready.

**Pull request closed without merging**
