### PR TITLE
Add New Relic exporter documentation

### PR DESCRIPTION
**Pull request by alanwest**
Adds documentation originally drafted in issue #34 for New Relic's exporter for the AWS OTel Collector.

There is an [open question](https://github.com/aws-otel/aws-otel.github.io/issues/34#issuecomment-742172085) on the issue requesting a recommendation regarding the sample yaml config contained in this documentation. Please offer any input.

### CODE REVIEW

**Comment by alanwest** [comment]
@alolita @elucus

Additional information has been added for our configuration options. There is a link to New Relic documentation concerning endpoints - the link may not work but should be available soon.

**Review by alolita — COMMENTED** [review]
Can you add Support links and contact info too. Thanks.

**Comment by elucus** [comment]
Hi @alolita, I've added the support contact details.

**Review by mxiamxia — APPROVED** [review]
LGTM! Thanks.

**Review by alolita — APPROVED** [review]

**Pull request merged**
