### PR TITLE
AppDynamics documentation for AWS Open Telemetry

### PR DESCRIPTION
**Pull request by okilker**
This is the Getting Started documentation for AppDynamics support for AWS OpenTelemetry.

- Includes getting started information

- the images referenced in our .mdx file are commited to `src/assets/img`folder.

### CODE REVIEW

**Comment by markTatAppD** [comment]
Is OTel the best, most official abbreviation for “OpenTelemetry”? Pavan was mentioning it should be changed, but I do not know to what.

**Comment by tedsuo** [comment]
We've never settled on a capitalization, but yes, "OTel" is the abbreviation we go by. (OT was OpenTracing)

**Review by alolita — COMMENTED** [review]
@okilker Please correct - 

OTLP (Online Transaction Processing) to OpenTelemetry Protocol

**Comment by okilker** [comment]
> OTLP (Online Transaction Processing) to OpenTelemetry Protocol

@alolita Done!

**Comment by okilker** [comment]
Hi @alolita , should I close this pull request, and open a new one for the OTLP file?

**Review by okilker — COMMENTED** [review]
@alolita , the new OTLP exporter page with AppD is ready for review.

**Review by alolita — APPROVED** [review]

**Pull request merged**
